### ISSUE TITLE
Go back to root path does not work

### ISSUE THREAD

**Issue by oggers** [guillotinaweb/angular-traversal#22]
When you go back (browser arrow) an event gets fired by the Location service. The subscription in class TraverserOutlet.ngOnInit takes care of this and consecuently traverses to the new url. But when going back to the root the url is an `<empty string>` and the traverser changes the url in the browser but does no change the context.

I have changed it and it seems to work, but I do not know much of this package, so I don't know any sideeffects this can cause, maybe someone with more knowledge of this package can check it.
```
    ngOnInit() {
        ...
        if (!this.noAutoTraverse) {
            this.location.subscribe(loc => {
                this.traverser.traverse(loc.url || '/', false);  // when empty string traverse to /
            });
        }
    }
```

Other workaround could be to implement a normalizer like this:

```
@Injectable()
export class RootPathNormalizer extends Normalizer {
    normalize(path: string): string {
        if ( path === '' ) {
            // if the path is empty we are at root, therefore substitute it
            // for '/' in order to traverse correctly to the root.
            return '/';
        } else {
            return path;
        }
    }
}
```

**Comment by ebrehault** [comment]
Hi @oggers,
I think the first solution you propose it the best one.
I will make that change soon (unless you already have a branch with this fix so you just need to make the pull request).

**Comment by oggers** [comment]
Hi @ebrehault,
I have just created the pull request.

Thanks.
